[package]
name = "ormlite-macro"
version = "0.16.0"
edition = "2021"
description = "An ORM for people who love SQL. Use the `ormlite` crate, not this one."
authors = ["Kurt Wolf <kurtwolfbuilds@gmail.com>"]
license = "MIT"
repository = "https://github.com/kurtbuilds/ormlite"

[lib]
proc-macro = true

[features]
postgres = []
sqlite = []
mysql = []
runtime-tokio-rustls = ["sqlx/runtime-tokio-rustls"]

default-sqlite = ["sqlite"]
default-postgres = ["postgres"]
default-mysql = ["mysql"]

[dependencies]
syn = { version = "1.0.82", features = ["derive", "parsing"] }
quote = "1.0.10"
proc-macro2 = "1.0.49"
ormlite-core = { path = "../core", version = "0.16.0" }
ormlite-attr = { path = "../attr", version = "0.16" }
sqlx = "0.6.0"
lazy_static = "1.4.0"
once_cell = "1.17.1"
itertools = "0.10.5"
