[package]
name = "ormlite-cli"
version = "0.8.0"
edition = "2021"
description = "An ORM for people who love SQL. Use the `ormlite` crate, not this one."
authors = ["Kurt Wolf <kurtwolfbuilds@gmail.com>"]
license = "MIT"
repository = "https://github.com/kurtbuilds/ormlite"

[[bin]]
name = "ormlite"
path = "src/main.rs"

[features]
#mysql = ["sqlx/mysql"]
#sqlite = ["sqlx/sqlite"]
#postgres = ["sqlx/postgres"]
#runtime-tokio-rustls = ["sqlx/runtime-tokio-rustls"]
default = ["ormlite/postgres", "ormlite/uuid", "ormlite/time", "ormlite/json"]

[dependencies]
anyhow = "1.0.68"
time = { version = "0.3.5", features = ["formatting"] }
clap = { version = "4.0.32", features = ["derive"] }
ormlite = { version = "0.8.0", path = "../ormlite" }
ormlite-core = { version = "0.8.0", path = "../core" }
ormlite-attr = { version = "0.8.0", path = "../attr" }
tokio = { version = "1", features = ["full"] }
sqlmo = { version = "0.7.6", features = ["sqlx"] }
syn = "1.0.107"
proc-macro2 = "1.0.49"
url = "2.3.1"
sha2 = "0.10.6"
regex = "1.7.0"

[dev-dependencies]
assert_matches = "1.5.0"
