[package]
name = "ormlite-cli"
version = "0.3.2"
edition = "2021"
description = "An ORM for people who love SQL. Use the `ormlite` crate, not this one."
authors = ["Kurt Wolf <kurtwolfbuilds@gmail.com>"]
license = "MIT"
repository = "https://github.com/kurtbuilds/ormlite"

[features]
#mysql = ["sqlx/mysql"]
#sqlite = ["sqlx/sqlite"]
#postgres = ["sqlx/postgres"]
#runtime-tokio-rustls = ["sqlx/runtime-tokio-rustls"]
default = ["ormlite/postgres", "ormlite/uuid", "ormlite/time", "ormlite/json"]

[dependencies]
anyhow = "1.0.68"
time = { version = "0.3.5", features = ["formatting"] }
clap = { version = "4.0.32", features = ["derive"] }
ignore = "0.4.18"
ormlite = { version = "0.3.2", path = "../ormlite" }
ormlite-attr = { version = "0.3.2", path = "../attr" }
tokio = { version = "1.15.0", features = ["full"] }
sqldiff = "0.2.4"
syn = "1.0.107"
proc-macro2 = "1.0.49"

[dev-dependencies]
assert_matches = "1.5.0"
