[package]
name = "ormlite-cli"
version = "0.3.2"
edition = "2021"
description = "An ORM for people who love SQL. Use the `ormlite` crate, not this one."
authors = ["Kurt Wolf <kurtwolfbuilds@gmail.com>"]
license = "MIT"
repository = "https://github.com/kurtbuilds/ormlite"

[features]
#mysql = ["sqlx/mysql"]
#sqlite = ["sqlx/sqlite"]
#postgres = ["sqlx/postgres"]
#runtime-tokio-rustls = ["sqlx/runtime-tokio-rustls"]
default = [
    "ormlite/postgres",
    "ormlite/sqlite",
    "ormlite/uuid",
    "ormlite/time",
    "ormlite/json",
]

[dependencies]
anyhow = "1.0.68"
time = { version = "0.3.5", features = ["formatting"] }
clap = { version = "4.0.32", features = ["derive"] }
ignore = "0.4.18"
ormlite = { version = "0.3.2", path = "../ormlite" }
sqldiff = "0.2.3"
syn = "1.0.107"
