[package]
name = "ormlite"
version = "0.7.0"
edition = "2021"
authors = ["Kurt Wolf <kurtwolfbuilds@gmail.com>"]
description = "An ORM for people who love SQL"
license = "MIT"
repository = "https://github.com/kurtbuilds/ormlite"
homepage = "https://github.com/kurtbuilds/ormlite"
documentation = "https://docs.rs/ormlite"
autotests = false
readme = "../README.md"

[package.metadata.docs.rs]
features = ["postgres", "runtime-tokio-rustls"]

[[test]]
name = "tests"
path = "tests/suite.rs"

[features]
mysql = ["sqlx/mysql", "ormlite-macro/mysql"]
sqlite = ["sqlx/sqlite", "ormlite-macro/sqlite", "ormlite-core/sqlite"]
postgres = ["sqlx/postgres", "ormlite-macro/postgres", "ormlite-core/postgres"]
runtime-tokio-rustls = ["ormlite-macro/runtime-tokio-rustls", "sqlx/runtime-tokio-rustls", "ormlite-core/runtime-tokio-rustls"]
uuid = ["sqlx/uuid"]
chrono = ["sqlx/chrono"]
time = ["sqlx/time"]
json = ["sqlx/json"]

[dependencies]
sqlx = { version = "0.6.0" }
tokio = { version = "1.15.0", features = ["full"] }
ormlite-macro = { path = "../macro" , version = "0.7.0"}
ormlite-core = { path = "../core" , version = "0.7.0"}
sqlx-core = "0.6.2"

[dev-dependencies]
trybuild = { version = "1.0.49", features = ["diff"] }
env_logger = "0.9.0"
uuid = { version = "1.1.2", features = ["serde", "v4"] }
