[package]
name = "ormlite-core"
version = "0.20.1"
edition = "2021"
description = "An ORM for people who love SQL. Use the `ormlite` crate, not this one."
authors = ["Kurt Wolf <kurtwolfbuilds@gmail.com>"]
license = "MIT"
repository = "https://github.com/kurtbuilds/ormlite"

[features]
mysql = ["sqlx/mysql"]
sqlite = ["sqlx/sqlite"]
postgres = ["sqlx/postgres"]
runtime-tokio-rustls = ["sqlx/runtime-tokio-rustls"]

[dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3"
sqlx = "0.8.1"
sqlparser = "0.50.0"
thiserror = "1"
sqlmo = "0.17.0"
ormlite-attr = { path = "../attr" , version = "0.20" }
anyhow = "1"
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
syn = "2.0.77"
proc-macro2 = "1.0.86"

[dev-dependencies]
syn = "2"
assert_matches = "1"
uuid = { version = "1", features = ["serde", "v4"] }
