[package]
name = "ormlite-core"
version = "0.10.1"
edition = "2021"
description = "An ORM for people who love SQL. Use the `ormlite` crate, not this one."
authors = ["Kurt Wolf <kurtwolfbuilds@gmail.com>"]
license = "MIT"
repository = "https://github.com/kurtbuilds/ormlite"

[features]
mysql = ["sqlx/mysql"]
sqlite = ["sqlx/sqlite"]
postgres = ["sqlx/postgres"]
runtime-tokio-rustls = ["sqlx/runtime-tokio-rustls"]

[dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3.25"
sqlx = "0.6.0"
sqlparser = "0.28.0"
thiserror = "1.0.30"
sqlmo = "0.10"
ormlite-attr = { path = "../attr", version = "0.10.1" }
anyhow = "1.0.69"

[dev-dependencies]
syn = "1.0.108"
assert_matches = "1.5.0"