[package]
name = "ormlite-core"
version = "0.3.2"
edition = "2021"
description = "An ORM for people who love SQL. Use the `ormlite` crate, not this one."
authors = ["Kurt Wolf <kurtwolfbuilds@gmail.com>"]
license = "MIT"
repository = "https://github.com/kurtbuilds/ormlite"

[features]
mysql = ["sqlx/mysql"]
sqlite = ["sqlx/sqlite"]
postgres = ["sqlx/postgres"]

runtime-tokio-rustls = ["sqlx/runtime-tokio-rustls"]

[dependencies]
datetime = "0.5.2"
futures-core = "0.3.19"
log = "0.4.14"
tokio = { version = "1", features = ["full"] }
futures = "0.3.19"
sqlx = "0.6.0"
sqlparser = "0.28.0"
thiserror = "1.0.30"
